ALTER TABLE "melhoria" ALTER COLUMN desc_problema DROP NOT NULL;
ALTER TABLE "melhoria" ALTER COLUMN desc_melhoria DROP NOT NULL;
ALTER TABLE "melhoria" ALTER COLUMN data DROP NOT NULL;
ALTER TABLE "melhoria" ALTER COLUMN status DROP NOT NULL;
ALTER TABLE "melhoria" ALTER COLUMN aprovacao DROP NOT NULL;
